name: Bump Version on master
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn lerna bootstrap
      - name: Bump version to first alpha of next minor version
        run: |
          yarn bump-version preminor
      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: lerna.json,packages/*/package.json
          commit-message: Update package.json version to next preminor because of recent release
          signoff: true
          delete-branch: true
          title: Update version to next preminor
          labels: chore
