name: Bump Version on master
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Bump version to first alpha of next minor version
        id: bump
        run: |
          CURRENT_VERSION=$(cat lerna.json | jq .version --raw-output)

          if ! [[ "${CURRENT_VERSION}" =~ ^\d+\.\d+\.0$ ]]; then
            echo "Not a minor release"
            echo "status=skip" >> $GITHUB_OUTPUT
            exit 0
          fi

          yarn bump-version preminor

          echo "status=create" >> $GITHUB_OUTPUT
      - uses: peter-evans/create-pull-request@v4
        if: ${{ steps.bump.outputs.status == 'create' }}
        with:
          add-paths: lerna.json,packages/*/package.json
          commit-message: Update package.json version to next preminor because of recent release
          signoff: true
          delete-branch: true
          title: Update version to next preminor
          labels: skip-changelog
