name: Require Milestone
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Require Milestone
        run: |
          exit $(echo "${{ toJson(github.event.pull_request.milestone) }}" | jq 'if . == null then 1 else 0 end')
